#!/bin/bash
# Ignore branches with specific names
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(main develop test)
fi
# Get the name of the current branch
BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"
# Check if current branch should be ignored
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)
# Add branch name to commit messages
if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  MESSAGE="\
# Forneça uma breve descrição para o commit após o nome da branch\n\
$BRANCH_NAME - \n\
\n\
# Forneça os tópicos que descrevem o que foi feito neste commit\n\
- \n\
"

  sed -i.bak -e "1s/^/$MESSAGE/" $1
fi
